run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
linters:
  disable-all: true
  enable:
  # default linters
  - errcheck
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - typecheck
  - unused

  # additional linters
  - errorlint
  - errname
  - gocyclo
  - goimports
  - misspell
  - gofmt
  - importas
  - goconst
  - gocritic
  - misspell
