apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: api-server
spec:
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: api-server
        image: api-server-image
        ports:
        - containerPort: 8082
        env:
        - name: KRATOS_ADMIN_URL
          value: http://kratos-admin.kratos
        - name: KRATOS_PUBLIC_URL
          value: http://kratos-public.kratos
        - name: KETO_READ_REMOTE
          value: keto-read.keto:80
        - name: KETO_WRITE_REMOTE
          value: keto-write.keto:80
        - name: HYDRA_ADMIN_URL
          value: http://hydra-admin.hydra:4445
---
apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  selector:
    app: api-server
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082
