adminPassword: strongpassword
grafana.ini:
  server:
    root_url: https://grafana.localhost.pluraldev.sh:4455/
  auth.generic_oauth:
    name: Hydra
    enabled: true
    allow_sign_up: true
    client_id: a1077f47-b4cc-4bc0-9fba-0c39c35de5cd
    client_secret: rZnw8ALOfdrgS1i2ZStXk0mPpfyvcmaI
    scopes: openid profile offline_access
#    auth_url: http://hydra-public.hydra:4444/oauth2/auth
    token_url: http://hydra-public.hydra:4444/oauth2/token
    api_url: http://hydra-public.hydra:4444/userinfo
    auth_url: https://hydra.localhost.pluraldev.sh:4455/oauth2/auth
#    token_url: https://hydra.localhost.pluraldev.sh:4455/oauth2/token
#    api_url: https://hydra.localhost.pluraldev.sh:4455/userinfo
