package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"github.com/pluralsh/trace-shield-controller/api/observability/v1alpha1"
	"github.com/pluralsh/trace-shield/graph/generated"
)

// RequestRate is the resolver for the requestRate field.
func (r *lokiLimitsResolver) RequestRate(ctx context.Context, obj *v1alpha1.LokiLimits) (*float64, error) {
	panic(fmt.Errorf("not implemented: RequestRate - requestRate"))
}

// LokiLimits returns generated.LokiLimitsResolver implementation.
func (r *Resolver) LokiLimits() generated.LokiLimitsResolver { return &lokiLimitsResolver{r} }

type lokiLimitsResolver struct{ *Resolver }
