package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"strings"

	"github.com/pluralsh/trace-shield-controller/api/observability/v1alpha1"
	"github.com/pluralsh/trace-shield/graph/generated"
	"github.com/pluralsh/trace-shield/graph/model"
)

// Types is the resolver for the types field.
func (r *blockedQueryResolver) Types(ctx context.Context, obj *v1alpha1.BlockedQuery) ([]model.BlockedQueryType, error) {
	types := strings.Split(*obj.Types, ",")
	output := make([]model.BlockedQueryType, len(types))
	for i, t := range types {
		output[i] = model.BlockedQueryType(t)
	}
	return output, nil
}

// BlockedQuery returns generated.BlockedQueryResolver implementation.
func (r *Resolver) BlockedQuery() generated.BlockedQueryResolver { return &blockedQueryResolver{r} }

type blockedQueryResolver struct{ *Resolver }
