package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/pluralsh/trace-shield/graph/model"
)

// AcceptOAuth2ConsentRequest is the resolver for the acceptOAuth2ConsentRequest field.
func (r *mutationResolver) AcceptOAuth2ConsentRequest(ctx context.Context, challenge string, grantAccessTokenAudience []string, grantScope []string, remember *bool, rememberFor *int64) (*model.OAuth2RedirectTo, error) {
	return r.C.AcceptOAuth2ConsentRequest(ctx, challenge, grantAccessTokenAudience, grantScope, remember, rememberFor)
}

// RejectOAuth2ConsentRequest is the resolver for the rejectOAuth2ConsentRequest field.
func (r *mutationResolver) RejectOAuth2ConsentRequest(ctx context.Context, challenge string) (*model.OAuth2RedirectTo, error) {
	return r.C.RejectOAuth2ConsentRequest(ctx, challenge)
}

// Oauth2ConsentRequest is the resolver for the oauth2ConsentRequest field.
func (r *queryResolver) Oauth2ConsentRequest(ctx context.Context, challenge string) (*model.OAuth2ConsentRequest, error) {
	return r.C.GetOAuth2ConsentRequest(ctx, challenge)
}
