package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"github.com/pluralsh/trace-shield/graph/model"
)

// AcceptOAuth2LoginRequest is the resolver for the acceptOAuth2LoginRequest field.
func (r *mutationResolver) AcceptOAuth2LoginRequest(ctx context.Context, challenge string, acr *string, amr []string, context map[string]interface{}, remember *bool, rememberFor *int64, subject string) (*model.OAuth2RedirectTo, error) {
	panic(fmt.Errorf("not implemented: AcceptOAuth2LoginRequest - acceptOAuth2LoginRequest"))
}

// RejectOAuth2LoginRequest is the resolver for the rejectOAuth2LoginRequest field.
func (r *mutationResolver) RejectOAuth2LoginRequest(ctx context.Context, challenge string) (*model.OAuth2RedirectTo, error) {
	panic(fmt.Errorf("not implemented: RejectOAuth2LoginRequest - rejectOAuth2LoginRequest"))
}

// Oauth2LoginRequest is the resolver for the oauth2LoginRequest field.
func (r *queryResolver) Oauth2LoginRequest(ctx context.Context, challenge string) (*model.OAuth2LoginRequest, error) {
	panic(fmt.Errorf("not implemented: Oauth2LoginRequest - oauth2LoginRequest"))
}
