package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"github.com/pluralsh/trace-shield/graph/model"
)

// AcceptOAuth2LoginRequest is the resolver for the acceptOAuth2LoginRequest field.
func (r *mutationResolver) AcceptOAuth2LoginRequest(ctx context.Context, challenge string, acr *string, amr []string, context map[string]interface{}, remember *bool, rememberFor *int64, subject string) (*model.OAuth2RedirectTo, error) {
	return r.C.AcceptOAuth2LoginRequest(ctx, challenge, acr, amr, context, remember, rememberFor, subject)
}

// RejectOAuth2LoginRequest is the resolver for the rejectOAuth2LoginRequest field.
func (r *mutationResolver) RejectOAuth2LoginRequest(ctx context.Context, challenge string) (*model.OAuth2RedirectTo, error) {
	return r.C.RejectOAuth2LoginRequest(ctx, challenge)
}

// Oauth2LoginRequest is the resolver for the oauth2LoginRequest field.
func (r *queryResolver) Oauth2LoginRequest(ctx context.Context, challenge string) (*model.OAuth2LoginRequest, error) {
	return r.C.GetOAuth2LoginRequest(ctx, challenge)
}
