package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"encoding/json"

	"github.com/pluralsh/trace-shield-controller/api/observability/v1alpha1"
	"github.com/pluralsh/trace-shield/graph/generated"
)

// Value is the resolver for the value field.
func (r *matchPolicyAttributeResolver) Value(ctx context.Context, obj *v1alpha1.MatchPolicyAttribute) (map[string]interface{}, error) {
	output := make(map[string]interface{})

	err := json.Unmarshal(obj.Value.Raw, &output)
	if err != nil {
		return nil, err
	}
	return output, nil
}

// MatchPolicyAttribute returns generated.MatchPolicyAttributeResolver implementation.
func (r *Resolver) MatchPolicyAttribute() generated.MatchPolicyAttributeResolver {
	return &matchPolicyAttributeResolver{r}
}

type matchPolicyAttributeResolver struct{ *Resolver }
