package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"encoding/json"
	"fmt"

	"github.com/pluralsh/trace-shield-controller/api/observability/v1alpha1"
	"github.com/pluralsh/trace-shield/graph/generated"
	"github.com/pluralsh/trace-shield/graph/model"
)

// Value is the resolver for the value field.
func (r *matchPolicyAttributeResolver) Value(ctx context.Context, obj *v1alpha1.MatchPolicyAttribute) (map[string]interface{}, error) {
	output := make(map[string]interface{})

	err := json.Unmarshal(obj.Value.Raw, &output)
	if err != nil {
		return nil, err
	}
	return output, nil
}

// MetricsGeneratorProcessorSpanMetricsFilterPolicies is the resolver for the metricsGeneratorProcessorSpanMetricsFilterPolicies field.
func (r *tempoLimitsInputResolver) MetricsGeneratorProcessorSpanMetricsFilterPolicies(ctx context.Context, obj *v1alpha1.TempoLimitsInput, data []*model.FilterPolicyInput) error {
	panic(fmt.Errorf("not implemented: MetricsGeneratorProcessorSpanMetricsFilterPolicies - metricsGeneratorProcessorSpanMetricsFilterPolicies"))
}

// MetricsGeneratorProcessorSpanMetricsDimensionMappings is the resolver for the metricsGeneratorProcessorSpanMetricsDimensionMappings field.
func (r *tempoLimitsInputResolver) MetricsGeneratorProcessorSpanMetricsDimensionMappings(ctx context.Context, obj *v1alpha1.TempoLimitsInput, data []*model.DimensionMappingsInput) error {
	panic(fmt.Errorf("not implemented: MetricsGeneratorProcessorSpanMetricsDimensionMappings - metricsGeneratorProcessorSpanMetricsDimensionMappings"))
}

// MatchPolicyAttribute returns generated.MatchPolicyAttributeResolver implementation.
func (r *Resolver) MatchPolicyAttribute() generated.MatchPolicyAttributeResolver {
	return &matchPolicyAttributeResolver{r}
}

// TempoLimitsInput returns generated.TempoLimitsInputResolver implementation.
func (r *Resolver) TempoLimitsInput() generated.TempoLimitsInputResolver {
	return &tempoLimitsInputResolver{r}
}

type matchPolicyAttributeResolver struct{ *Resolver }
type tempoLimitsInputResolver struct{ *Resolver }
