package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"
	"fmt"

	"github.com/pluralsh/trace-shield-controller/api/observability/v1alpha1"
	"github.com/pluralsh/trace-shield/graph/generated"
)

// RequestRate is the resolver for the requestRate field.
func (r *tempoLimitsResolver) RequestRate(ctx context.Context, obj *v1alpha1.TempoLimits) (*float64, error) {
	panic(fmt.Errorf("not implemented: RequestRate - requestRate"))
}

// TempoLimits returns generated.TempoLimitsResolver implementation.
func (r *Resolver) TempoLimits() generated.TempoLimitsResolver { return &tempoLimitsResolver{r} }

type tempoLimitsResolver struct{ *Resolver }
